[project]
name = "erp-enterprise-app"
authors = [{ name = "hoangtien07", email = "tienproanhhp@gmail.com" }]
description = "EWCP ERP custom Frappe app — erp-ewcp-bridge + VN business customizations"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
dependencies = []

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.bench.frappe-dependencies]
frappe = "~16.0.0"
erpnext = "~16.0.0"
